name: Print Pull Request Context
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print context
        shell: cmd
        run: |
          echo "${{ toJSON(github) }}"
          Write-Host "${{ toJSON(github) }}"
